// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class AchievementClientBindings
    {
        readonly ICloudCodeService k_Service;
        public AchievementClientBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<List<BlocksGameModule.Achievements.Achievement>> GetAchievements(string playerId)
        {
            return await k_Service.CallModuleEndpointAsync<List<BlocksGameModule.Achievements.Achievement>>(
                "BlocksGameModule",
                "GetAchievements",
                new Dictionary<string, object>()
                {
                    {"playerId", playerId},
                });
        }

        public async Task<BlocksGameModule.Achievements.AchievementRecord> UnlockAchievement(string achievementId)
        {
            return await k_Service.CallModuleEndpointAsync<BlocksGameModule.Achievements.AchievementRecord>(
                "BlocksGameModule",
                "UnlockAchievement",
                new Dictionary<string, object>()
                {
                    {"achievementId", achievementId},
                });
        }

        public async Task ResetAllAchievements()
        {
            await k_Service.CallModuleEndpointAsync(
                "BlocksGameModule",
                "ResetAllAchievements",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<BlocksGameModule.Achievements.AchievementRecord> UpdateAchievementProgress(string achievementId, int count)
        {
            return await k_Service.CallModuleEndpointAsync<BlocksGameModule.Achievements.AchievementRecord>(
                "BlocksGameModule",
                "UpdateAchievementProgress",
                new Dictionary<string, object>()
                {
                    {"achievementId", achievementId},
                    {"count", count},
                });
        }
    }
}
