// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.BlocksGameModule.Achievements
{
    public partial class Achievement
    {
        public string Id;
        public AchievementDefinition Definition;
        public AchievementRecord Record;

        [Preserve]
        public Achievement ()
        {
        }
    }
}