// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.BlocksGameModule.Achievements
{
    public partial class AchievementRecord
    {
        public string Id;
        public bool Unlocked;
        public int ProgressCount;

        [Preserve]
        public AchievementRecord ()
        {
        }
    }
}