// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.BlocksGameModule.Achievements
{
    public partial class AchievementDefinition
    {
        public string Icon;
        public string Id;
        public string Title;
        public string Description;
        public bool IsHidden;
        public int ProgressTarget;

        [Preserve]
        public AchievementDefinition ()
        {
        }
    }
}