// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.BlocksGameModule.Leaderboards
{
    public partial class NumberGameResult
    {
        public int Goal;
        public int Score;

        [Preserve]
        public NumberGameResult ()
        {
        }
    }
}